### ISSUE TITLE
Implement more normalizations

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/normalize-url#1]
I implemented the most important ones, but I think there's some missing:

http://en.wikipedia.org/wiki/URL_normalization

Also open to consider other normalizations not listed in the above page.

**Comment by DaSchTour** [comment]
I think the following could be very helpful
http:// -> //
https:// -> //
For pages served over http and https you can make sure that protocols match

**Comment by sindresorhus** [comment]
@DaSchTour That's an anti-pattern: https://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by TrySound** [comment]
Hi @sindresorhus. Did you considered adding email url normalisation like `user@email.com` -> `mailto:user@email.com`. Currently it's normalised into `email.com`.

**Comment by sindresorhus** [comment]
@TrySound I think that's outside the scope of this module. `user@email.com` is not a valid URL.

**Comment by sindresorhus** [comment]
Closing as I think we have implemented most of the normalizations.
