### ISSUE TITLE
Not an issue: Add it to an utility library (like lodash, underscore, etc.)

### ISSUE THREAD

**Issue by MikeVelazcoMtz** [sindresorhus/normalize-url#101]
I just love what you do with this library!, but I think the best way to take the best from this library would be to merge it into a larger utility project.

Just a suggestion.

Thanks for your work on this!

**Comment by sindresorhus** [comment]
While it's good to try to combine related things into a library, I don't really see what this could be combined with and it's large enough to make sense an individual package.
