### ISSUE TITLE
[v4] searchParams.sort is not a function

### ISSUE THREAD

**Issue by nghiepit** [sindresorhus/normalize-url#106]
Hi guys,

Sometimes, I get an error on Chrome Mobile 77
```
searchParams.sort is not a function
```

**Comment by sindresorhus** [comment]
The `.sort()` method should exist: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/sort

So either you're including some polyfill that doesn't implement the `.sort()` method or it's a bug in Chrome. Chrome 77 is not the latest version, so this might have been fixed already. If not, you should report it to Chrome.
