### ISSUE TITLE
Equal sign is added to end of empty query string variable

### ISSUE THREAD

**Issue by mustafa0x** [sindresorhus/normalize-url#112]
```
> normalize_url('example.com/?a');
http://example.com/?a=

> (new URL('http://example.com/?a')).toString()
http://example.com/?a
```

**Comment by sindresorhus** [comment]
That looks like a bug, yes.

**Comment by muuvmuuv** [comment]
It seems `urlObj.searchParams.sort();` is doing this. I will look into it if I can find a simple fix.

**Comment by muuvmuuv** [comment]
So it seems this is by design according to the spec: 

- https://url.spec.whatwg.org/#dom-urlsearchparams-sort
- https://url.spec.whatwg.org/#concept-urlencoded-serializer

I created an issue anyway to discuss if this could be made optional if it makes sense so please add your use case @mustafa0x.

**Comment by mustafa0x** [comment]
See how the original Wiki (wiki.c2.com) links to pages:

- https://wiki.c2.com/?WikiWikiWeb
- https://wiki.c2.com/?OneMinuteWiki

**Comment by muuvmuuv** [comment]
So they seemed to be clear enough in the referenced issues at *whatwg*. This is the spec and therefore I wouldn't implement any transformation in `normalize-url` since it should normalize it TO the spec. What do you think @sindresorhus ?

**Comment by mustafa0x** [comment]
Thanks for the research @muuvmuuv.

FWIW, this affects my web app since adding `=` causes a cache-miss.
