### ISSUE TITLE
Option to keep trailing slash in all cases

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/normalize-url#119]
I'd like to keep the output of this module as close as possible to the input and that means to also retain a `pathname` of `/` in a case like this:

````js
normalizeUrl('http://sindresorhus.com/', {removeTrailingSlash: false});
//=> 'http://sindresorhus.com'
````

While I generally think `removeTrailingSlash: false` should not remove any slashes in `pathname`, I could see a option like `keepTrailingSlashOnEmptyPath` being added for compatibilty.

This option would be useful because it is hard to work around because `URL()` will always output a `pathname` of `/` regardless whether that slash is present or not:

````console
> new URL("https://sindresorhus.com").pathname
'/'
> new URL("https://sindresorhus.com/").pathname
'/'
````

**Comment by sindresorhus** [comment]
> I'd like to keep the output of this module as close as possible to the input

Why does it matter? There are many things this package does that change the input. That's the whole point of it. What's your use-case for needing this?

> I could see a option like keepTrailingSlashOnEmptyPath being added for compatibilty.

Yes, it would have to be a separate option.

**Comment by silverwind** [comment]
> There are many things this package does that change the input

Yeah and I have those all turned off for my case. But this trailing slash stripping is the only one I can not turn off.

> What's your use-case for needing this?

I'm using this module to URI-encode URL segments, punycode IDNs and get rid of double-encoding which are all valuable adjustments in itself.

 think stripping the trailing slash is a opinionated change that even goes against WHATWG recommendations to always have pathname set to `/` when not present. Browser also add this slash after entering a URL without one.

**Comment by silverwind** [comment]
Maybe we could add a third value `"all"` to the `removeTrailingSlash` for this.

**Comment by sindresorhus** [comment]
Alright. I'm open to adding something for this.

**Comment by sindresorhus** [comment]
> Maybe we could add a third value "none" to the removeTrailingSlash option for this.

I don't think that would be clear enough. `none` is kinda like `false` in my mind.

**Comment by silverwind** [comment]
Any better ideas for overloading `removeTrailingSlash` or would it better be a new option?

**Comment by silverwind** [comment]
https://github.com/sindresorhus/normalize-url/pull/120
