### ISSUE TITLE
Require TLD

### ISSUE THREAD

**Issue by varunsrin** [sindresorhus/normalize-url#126]
Thoughts on adding a feature to require TLD's in the url?  It would raise an error on `http://google` but not `http://google.com` or `http://google.abcdefg`  

I can make a PR if that direction makes sense.

**Comment by sindresorhus** [comment]
Why? What's the use-case?

**Comment by hiluw** [comment]
If I'm understanding the issue, someone could buy google.foo and spoof it.

**Comment by sindresorhus** [comment]
I'm going to pass on this. This package is about normalization, not validation.
