### ISSUE TITLE
foo:bar can not be normalized?

### ISSUE THREAD

**Issue by shrinktofit** [sindresorhus/normalize-url#127]
`foo:bar` is automatically converted into `http:foo:bar` by this lib.

**Comment by sindresorhus** [comment]
Yes, we assume `//` in the scheme. I guess we could loosen that. I don't remember if we made it strict or a reason.

https://github.com/sindresorhus/normalize-url/blob/ededdbe81b4d75e9065cbe626fe9c38bde175dcf/index.js#L95

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/normalize-url/commit/882cb84d5ecfeb1c29d7d19b18058730c6c08dc5
