### ISSUE TITLE
How do I get non stripped urls from given text

### ISSUE THREAD

**Issue by mifas** [sindresorhus/normalize-url#128]
When I pass below URL, these characters are removed ```!@#$```. But I'm expecting those characters should present. Is there I can make this changE?
```
getUrls(`https://abc.yahoo.co.jp!@#$`) -> `https://abc.yahoo.co.jp`
```

**Comment by sindresorhus** [comment]
Those characters are not valid in that place. After the TLD, there can be a `/`, `?`, or `#`. Normalize URLs does its job correctly here.
