### ISSUE TITLE
Strip text fragment option

### ISSUE THREAD

**Issue by adam-lynch** [sindresorhus/normalize-url#129]
https://web.dev/text-fragments/. Text fragments are currently supported in Edge, Chrome, and some mobile browsers. Google use/used them in search results.

Expected behaviour:

- https://example.com/page#:~:text=hello -> https://example.com/page
- https://example.com/page#main:~:text=hello -> https://example.com/page#main
- https://example.com/page#main -> https://example.com/page#main

I currently need to do this but I'm not sure many will so maybe it's not worth having to maintain an option for it.

**Comment by sindresorhus** [comment]
Yeah, good idea. PR welcome.

**Comment by adam-lynch** [comment]
So it would be a new option? E.g.

```
normalizeUrl('...', {stripHash: false, stripTextFragment: true});
```

**Comment by sindresorhus** [comment]
Correct
