### ISSUE TITLE
sortQueryParameters encodes the query string

### ISSUE THREAD

**Issue by freearhey** [sindresorhus/normalize-url#149]
Is it supposed to be like this?

**sortQueryParameters: true**

```js
normalizeUrl('http://sindresorhus.com/?url=http://example.com', {
    sortQueryParameters: true
});
//=> 'http://sindresorhus.com/?url=http%3A%2F%2Fexample.com'
```

**sortQueryParameters: false**

```js
normalizeUrl('http://sindresorhus.com/?url=http://example.com', {
    sortQueryParameters: false
});
//=> 'http://sindresorhus.com/?url=http://example.com'
```

**Comment by ludofischer** [comment]
That's unforunately expected since `normalize-url` uses `URL.searchParams()` under the hood which follows different rules from the IETF URI spec since it is based on the WHATWG URL spec https://nodejs.org/api/url.html#urlsearchparams.

**Comment by freearhey** [comment]
Got it.

**Comment by taoliujun** [comment]
why closed. how to resolve

**Comment by freearhey** [comment]
> why closed.

because my question was answered

> how to resolve

pass the output string through the [decodeURIComponent()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent):

```js
decodeURIComponent('http://sindresorhus.com/?url=http%3A%2F%2Fexample.com') 
// => 'http://sindresorhus.com/?url=http://example.com'
```

**Comment by ludofischer** [comment]
> 
> pass the output string through the [decodeURIComponent()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent):
> 
> ```js
> decodeURIComponent('http://sindresorhus.com/?url=http%3A%2F%2Fexample.com') 
> // => 'http://sindresorhus.com/?url=http://example.com'
> ```

Wow! Good find. But what if the original URL parameters were encoded?

**Comment by ludofischer** [comment]
I've made a PR to always decode the parameters, since after all the package name starts with `normalize-` :-)
