### ISSUE TITLE
Please tag version 4.5.1 on Github

### ISSUE THREAD

**Issue by mohe2015** [sindresorhus/normalize-url#156]
npm contains version https://www.npmjs.com/package/normalize-url/v/4.5.1 but this version is not tagged on Github.

Would be great if you could tag it.

**Comment by raphaelbs** [comment]
Yes! I'm trying to compare the versions to double-check the changes and I couldn't find it.

**Comment by sindresorhus** [comment]
I forgot to tag it and I no longer have the branches, but this was the only change:

```diff
-const parts = urlString.match(/^data:(.*?),(.*?)(?:#(.*))?$/);
+const parts = urlString.match(/^data:([^,]*?),([^#]*?)(?:#(.*))?$/);
```
