### ISSUE TITLE
Add `package.json` to `exports`

### ISSUE THREAD

**Issue by redexp** [sindresorhus/normalize-url#157]
I'm using this module in react-native project and without next modification to `package.json` file it throws warning
```
warn Package normalize-url has been ignored because it contains invalid configuration. 
Reason: Package subpath './package.json' is not defined by "exports" in node_modules/normalize-url/package.json
```
Modification needed
```json
{
  "exports": {
    ".": "./index.js",
    "./package.json": "./package.json"
  }
}
```
I think it's because of `Introducing the "exports" field prevents consumers of a package from using any entry points that are not defined` [docs](https://nodejs.org/api/packages.html#package-entry-points) and webpack needs access to package.json

**Comment by sindresorhus** [comment]
This is a problem with React Native. You should report it on the React Native issue tracker instead. It's a losing battle to get every single package out there to manually expose package.json just for React Native.

**Comment by redexp** [comment]
@sindresorhus I have a lot installed packages and I was surprised when such small package like yours was first which throws any warnings. Changing `"exports": "./index.js"` to `"main": "index.js"` also works.
