### ISSUE TITLE
Strip ftp:// and ssh://

### ISSUE THREAD

**Issue by ozgurg** [sindresorhus/normalize-url#159]
_I accidentally pressed ENTER while creating the issue. 😄_ 

Is it possible to strip ftp:// and ssh://?

I tried these options but it didn't worked. Actually I want strip all protocols.

```js
defaultProtocol: "ftp:",
stripProtocol: true,
normalizeProtocol: true
```

**Comment by sindresorhus** [comment]
It only strips protocol for `http:` and `https:`. I should make that clearer in the docs. Stripping any protocol would make the URL become ambiguous. Why are you trying to do this?

**Comment by ozgurg** [comment]
> It only strips protocol for `http:` and `https:`. I should make that clearer in the docs. Stripping any protocol would make the URL become ambiguous. Why are you trying to do this?

I get the URL from an input, and it might contains ftp:// and ssh:// (and other protocols). So I want to strip all protocols. I would replace them with empty string but I wanted to know if the library can do this. If this isn't the target of the library, I'm OK with that.

By the way I agree with you in making that clearer in the docs.

**Comment by sindresorhus** [comment]
That's not a good use for this package. You can just use a simple regex instead. Docs improved.
