### ISSUE TITLE
Would you accept backport fixes to 6.x?

### ISSUE THREAD

**Issue by shellscape** [sindresorhus/normalize-url#164]
Just stopping by to see if you'd accept a PR that backported recent fixes to the 6.x versions. ESM is still a silly issue in a lot of ecosystems, and I'm working in one.

**Comment by sindresorhus** [comment]
I unfortunately don't have time to keep handling back ports. I only accept backporting security fixes now. I suggest just applying the fixes you need in a fork. Or use `await import(…)`.
