### ISSUE TITLE
Error using react testing library

### ISSUE THREAD

**Issue by italosantana** [sindresorhus/normalize-url#166]
![image](https://user-images.githubusercontent.com/48260257/169023313-632f6f48-8782-4396-8e87-1980cad7c080.png)

Using normalize-url latest version, and I am trying to render a component with react testing library and show this error.

In the error it says it's to fix "Must use import to load ES Module", and the babel-jest I'm using is already doing that. But it does not work!

Does anyone have an idea what it could be?

**Comment by italosantana** [comment]
@sindresorhus Do you have any idea what it could be?

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by beshur** [comment]
@italosantana, did you manage to implement the advice suggested by Sindre?

**Comment by italosantana** [comment]
> @italosantana, did you manage to implement the advice suggested by Sindre?

yes, @beshur! I was having a problem with jest. Putting in transforIgnorePatterns and it's worked for me.

```
transformIgnorePatterns: [
		"node_modules/(?!normalize-url/.*)",
	],
```

**Comment by beshur** [comment]
Thanks for reply, @italosantana.
That didn't help me.
Anything else maybe?
