### ISSUE TITLE
Fix Safari compatibility for version 6.1.0

### ISSUE THREAD

**Issue by omry-hay** [sindresorhus/normalize-url#168]
We are using version `v6.1.0` and can't upgrade since we still can't use pure ESM.
However this version is incompatible with Safari, and we are kind of stuck here.
Can you please release a new version with the fix for version `6.1.0`?

**Comment by hmelenok** [comment]
Not an excuse or anything but: 
![CleanShot 2022-08-18 at 19 02 55](https://user-images.githubusercontent.com/2149114/185441804-9a752aa9-8934-4e08-be8c-d2b9fadec357.png)

And usage stats show how much people **stuck** with 4.5.1:
![CleanShot 2022-08-18 at 19 02 30](https://user-images.githubusercontent.com/2149114/185441951-3f8c6089-cb0a-4070-ba6f-91f3ae37f3ec.png)

**Comment by hmelenok** [comment]
The problem is in unsupported by Safari regex patterns 
```
SyntaxError: Invalid regular expression: invalid group specifier name
```

https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group
