### ISSUE TITLE
Add `removePort` option

### ISSUE THREAD

**Issue by ianizaguirre** [sindresorhus/normalize-url#171]
In the Docs, you have an example that has a port on a url and then when you wrap the url with "normalizeUrl" the port is no longer included:
<img width="913" alt="image" src="https://user-images.githubusercontent.com/29879270/180018260-d1ce5d11-3713-4ba7-a84b-5da85b4bc462.png">

When I run this same example locally, the Port `:80/` is still included - which is different behavior from what your documentation example above shows:
<img width="657" alt="image" src="https://user-images.githubusercontent.com/29879270/180018771-ed1f4d57-f624-47bf-88da-a0d6c56286a8.png">

 How would I remove the `:80/` port portion of a url with your package ?
 
 
 I am pretty sure there is a bug because when I did another test the behavior is not consistent. As you can see in the image below, the results are not consistent just by changing a url from having `http` too `https` and also I see that just changing the actual number for the port in the url makes the behavior different too:
<img width="803" alt="image" src="https://user-images.githubusercontent.com/29879270/180027443-35e7fc3b-ae52-41ff-a570-72d2144d0f50.png">

**Comment by ianizaguirre** [comment]
> Why would it remove `80`? The default port for **HTTPS** is 443. I think the existing behavior is correct.

Hi, Thanks for your quick reply.

hmm, well in my case I wanted an option to remove the port so I can create a more user friendly/readable url. I used your library but had to do an additional step of regex to strip the `:#` port number from it. 

I had assumed your library would have let me remove the port (any port) on the url, instead of it deciding when a port should be removed or kept.

Do you think that adding an option to remove a port (any port found) to your library would be a feature you could implement?

**Comment by sindresorhus** [comment]
Removing port 80 from a HTTPS URL would could potentially break the URL, although unlikely. I'm ok with a `removePort: true` option. I think a boolean is enough for now. If people have a need for more, they can request it.

**Comment by ianizaguirre** [comment]
Nice, I can work on this task.

Just to get some clarity before I make a pull request, when you said:
> Removing port 80 from a HTTPS URL would could potentially break the URL, although unlikely.

When I add the `removePort` boolean option, I still make it remove all ports including port 80, right?

**Comment by loynoir** [comment]
I think `removePort` should be rename to `unsafeRemovePort`, or current naming style `forceRemovePort`.

Because [https://example.com:80](https://example.com:80) and [https://example.com](https://example.com) is **NOT SAME AT ALL**, they just happen to **LOOK** same in specific cases.

- [https://example.com:80](https://example.com:80)  Secure Connection Failed
- [https://example.com](https://example.com) Example Domain

**Comment by ianizaguirre** [comment]
ok sounds good. I will work on it

**Comment by ianizaguirre** [comment]
> Removing port 80 from a HTTPS URL would could potentially break the URL, although unlikely. I'm ok with a `removePort: true` option. I think a boolean is enough for now. If people have a need for more, they can request it.

Pull request has been created: https://github.com/sindresorhus/normalize-url/pull/174
