### ISSUE TITLE
Is there an (efficient) way to extract the domain only?

### ISSUE THREAD

**Issue by jahamed** [sindresorhus/normalize-url#182]
Using 'stripProtocol' to remove http/https but I would like to change 
```audlindin.is/##.owl-stage-outer```
to 
```audlindin.is```

Am I missing an option or is there an efficient way to do this?

Basically want to extract the domain name only if possible :)

**Comment by sindresorhus** [comment]
You can use `stripTextFragment: true` too. But it sound simpler to just do `new URL(url).hostname`.
