### ISSUE TITLE
Is Safari supported?

### ISSUE THREAD

**Issue by TristanH** [sindresorhus/normalize-url#183]
The readme says:

> If you need Safari support, use version 4: npm i normalize-url@4

However, it looks like Safari support was re-added here? https://github.com/sindresorhus/normalize-url/pull/148 (as of 7.0.1)

Can you clarify whether Safari (or any other browsers) are not supported?

If they are all supported, happy to open a PR to fix the docs.

**Comment by TristanH** [comment]
@sindresorhus friendly bump on this :)

**Comment by sindresorhus** [comment]
Yes, Safari is supported.

**Comment by TristanH** [comment]
great thanks!
