### ISSUE TITLE
Meow full url

### ISSUE THREAD

**Issue by wifiextender** [sindresorhus/normalize-url#20]
```javascript
var abs = function(url) {
    var alink = document.createElement('a');
    alink.setAttribute('href', url);
    return alink.href;
};

abs('MeowMeow');
// "https://github.com/sindresorhus/normalize-url/issues/MeowMeow"
```

**Comment by sindresorhus** [comment]
🐈

**Comment by sindresorhus** [comment]
Can you please elaborate?

**Comment by wifiextender** [comment]
I was mislead by the project title, tried to solve the help https://github.com/sindresorhus/normalize-url/pull/19 issue, but didn't noticed that your project is only meant to be used in node and not in the browser (client side).

**Comment by sindresorhus** [comment]
You can use it in the browser, but you need to [Browserify](http://browserify.org/) (or Webpack) it first.

**Comment by YuriGor** [comment]
Thank you @ghost for this tip, this is what I actually needed.
Actually even simpler in my case: just read `href` link element property instead of `getAttribute('href') )`
So, finally, I need no URL normalization at all.
