### ISSUE TITLE
Keep stripFragment while support AngularJS sites

### ISSUE THREAD

**Issue by kilik52** [sindresorhus/normalize-url#23]
some sites implemented with AngularJS have routes like this:

````
http://www.example.com/#/page1
http://www.example.com/#/page2
````

They are two different addresses, but will be normalized to one same url. 
I can set the stripFragment to false, but urls like 

````
http://www.example.com/bar.html#section1
http://www.example.com/bar.html#section2
````

will treated as two different urls.

Can both situation be satisfied at the same time?

**Comment by sindresorhus** [comment]
Too obscure of an use-case. The correct way to handle dynamic routes these days is with `pushState()` anyway.
