### ISSUE TITLE
Crash for some urls

### ISSUE THREAD

**Issue by kilik52** [sindresorhus/normalize-url#24]
normalizeUrl('http://tieba.baidu.com/f?kw=%C3%C0%CE%C4')

````
URIError: URI malformed
    at decodeURIComponent (native)
    at /node_modules/query-string/index.js:43:36
    at Array.forEach (native)
    at Object.exports.parse (/node_modules/query-string/index.js:32:17)
    at module.exports (/node_modules/normalize-url/index.js:104:36)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)

````

I've found the reason:  
%C3%C0%CE%C4 is GB2312 not UTF-8

Maybe you can change

```
val = val === undefined ? null : decodeURIComponent(val);
```

to

````
val = val === undefined ? null : val;
````

I don't think you really need to decode the value in order to normalize url.

**Comment by kilik52** [comment]
Another Url

http://bemaniwiki.com/index.php?REFLEC%20BEAT%20limelight%2F%B5%EC%B6%CA%CA%D1%B9%B9%C5%C0

this time, the key is the problem.

**Comment by sindresorhus** [comment]
That error is coming from another module, and yes, the decoding is necessary:

```js
'https://sindresorhus.com/?foo%3Dbar%20bar' === 'https://sindresorhus.com/?foo=bar bar';
//=> false

**Comment by kilik52** [comment]
You are right. 
May be you can add try/catch to decode it when it can be decoded.

**Comment by sindresorhus** [comment]
> May be you can add try/catch to decode it when it can be decoded.

Then you'll silently end up with undecoded URLs, which I think is worse. Rather, if you don't control the URLs you feed it, try/catch the call to this module and handle it yourself.
