### ISSUE TITLE
Missing url package as a dependency

### ISSUE THREAD

**Issue by joncursi** [sindresorhus/normalize-url#28]
The `url` package should be added to the list of dependencies in package.json. Otherwise, the dev will explicitly need to npm install `url` in order to use this package.

url is used here: https://github.com/sindresorhus/normalize-url/blob/master/index.js#L2

**Comment by sindresorhus** [comment]
`url` is a Node.js core package. https://nodejs.org/dist/latest-v6.x/docs/api/url.html

**Comment by joncursi** [comment]
Interesting. For what it's worth, I ran into this dependency issue when installing the package in a react native project.

**Comment by enapupe** [comment]
Ok but how does this package works on the browser since there's no `url` available? 😮

**Comment by enapupe** [comment]
Oh I see.. webpack is building my bundle and by change, I have that url package installed as another dependency dependency. Works by mere chance. I'm gonna add `url` as a dependency of that project of mine that uses `normalize-url`..
