### ISSUE TITLE
Not handling single quotes correctly

### ISSUE THREAD

**Issue by ben-eb** [sindresorhus/normalize-url#33]
Migrated from: https://github.com/ben-eb/postcss-normalize-url/issues/13

```js
const normalize = require("normalize-url");

console.log(normalize("http://example.com/foo\\'bar.jpg"));

//=> http://example.com/foo/%27bar.jpg
```

**Comment by sindresorhus** [comment]
What is the expected result?

**Comment by ben-eb** [comment]
Ah, sorry.

```js
/* Current */
"http://example.com/foo/%27bar.jpg"

/* Expected */
"http://example.com/foo%27bar.jpg"
```

I think the backslash before the `'` isn't necessary (but encoding the character should be). However I dug a little further and it looks like this is coming from `URL.parse`:

```
Url {
  protocol: 'http:',
  slashes: true,
  auth: null,
  host: 'example.com',
  port: null,
  hostname: 'example.com',
  hash: null,
  search: null,
  query: null,
  pathname: '/foo/%27bar.jpg',
  path: '/foo/%27bar.jpg',
  href: 'http://example.com/foo/%27bar.jpg' }
```

Note that this test passes:

```js
test('should handle single quotes', t => {
	t.is(m('http://example.com/foo\'bar.jpg'), 'http://example.com/foo%27bar.jpg');
});
```

But this does not:

```js
test('should handle escaped single quotes', t => {
	t.is(m('http://example.com/foo\\\'bar.jpg'), 'http://example.com/foo%27bar.jpg');
});
```

I'm not sure if accounting for what wrapping quotes a URL string uses is within the scope of this module but it would be important for my use case! 😄

**Comment by ben-eb** [comment]
Sorry to bother you with this Sindre, I'm going to fix this in cssnano instead by changing the wrapping quotes when possible. I don't think it should be this module's job to do.
