### ISSUE TITLE
Normalize HTTPS to HTTP

### ISSUE THREAD

**Issue by ScionOfBytes** [sindresorhus/normalize-url#34]
Currently http://wesbite.com
and https://website.com are treated differently.

**Comment by sindresorhus** [comment]
👍 Pull request welcome. Should be opt-in.

**Comment by venikman** [comment]
What about way around? If my input: `example.com` it will gimme `http://example.com` but I want `https://example.com'.

**Comment by sindresorhus** [comment]
Yes, open a new issue.
