### ISSUE TITLE
stripWWW strips domains too

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/normalize-url#38]
```js
normalize("www.com")
//-> http://com
```

This can be rectified with [strip-www](https://npmjs.com/strip-www).

**Comment by sindresorhus** [comment]
Can you do a PR?

**Comment by Schavras** [comment]
Hello! If no one is working on it right now, I would like to try. It's my first attempt to contribute to another open source project :)

**Comment by stevenvachon** [comment]
Feel free. If not, I'll try to get to it sometime next week.

**Comment by Schavras** [comment]
Can you give me some more information about the bug?
 It only don't work with URL `www.com` ?
Because I have done some tests with
- `http://testwww.com`
- `http://test.www.com`

and they passed the tests.

**Comment by stevenvachon** [comment]
The most important test case is listed above. Also, check out strip-www's test suite.

**Comment by Schavras** [comment]
I'm confused with the cases
`t.is(m('http://www.', opts), 'http://www.');`
`t.is(m('http://www', opts), 'http://www');`
from strip-www's test suite. Is those even valid domain names?

**Comment by stevenvachon** [comment]
They don't have to be valid domains.. they test that the input does not mutate invalid input. Also, "www" could be a local TLD.

**Comment by stevenvachon** [comment]
There's an edge case with stripping www subdomains with regexp:
```
www.www.domain.com
www.subdomain.domain.tld
```
will produce:
```
www.domain.com
subdomain.domain.tld
```

Because the regexp doesn't know which is the domain and which is the tld. This is where large libraries like [parse-domain](https://npmjs.com/parse-domain) provide support for tld's such as "co.uk"

**Comment by ethanbb** [comment]
Interesting - so the edge case of URLs like `www.www.domain.com` would actually cause normalize-url to no longer be idempotent (calling it once would produce `www.domain.com`, and then calling it a second time on the result would produce `domain.com`). As a solution, perhaps just let the stripWWW option strip all leading "www" subdomains? It seems like using "www" as a subdomain in two levels of a URL is asking for trouble anyway.

**Comment by stevenvachon** [comment]
It gets worse:
```
www.app.company.com
```
produces:
```
app.company.com
```
Technically, the subdomain is "www.app", since there is structurally no sub-subdomain.
