### ISSUE TITLE
WHATWG spec compliance

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/normalize-url#39]
Use [universal-url](https://npmjs.com/universal-url).

I've written a library that does, ~~but I'd prefer not to release a duplicate of this library~~. Perhaps we can collaborate.

**Comment by sindresorhus** [comment]
Sure, I invited you to the repo. What kind of changes are needed?

**Comment by sindresorhus** [comment]
> The Node.js shim does not currently support URLSearchParams. 

That's too bad. Any other shim we could use? I would really like to go full in on URL and URLSearchParams since that's clearly the future.

**Comment by stevenvachon** [comment]
Nope, there's nothing else. There're some browser-only shims that provide support, but they are otherwise not spec-compliant.

**Comment by stevenvachon** [comment]
> Sure, I invited you to the repo. What kind of changes are needed?

I already started releasing [minurl](https://npmjs.com/minurl). What do you think of the API, and how does it fit in with this repo? I'd built it to fit in with [relateurl](https://github.com/stevenvachon/relateurl) and [url-relation](https://npmjs.com/url-relation).

**Comment by sindresorhus** [comment]
`minurl` looks good, but has IMHO too many options. I've tried very hard with this module to only introduce options when actually required. For example, `options.removeEmptyHash` is moot as there's no good reason not to always do this.

**Comment by stevenvachon** [comment]
No good reason that we can foresee. So, while I do agree that that option is moot, someone may think otherwise and instead of involving myself/ourselves in their issue, they can refer to documentation. Every mutation is optional.

**Comment by stevenvachon** [comment]
A quick idea I just thought of could be for normalize-url to wrap minurl with:
* added support for string input (`URL` parsing)
* options abstracted and/or hidden

Though, it'd be better not to need a separate package

**Comment by stevenvachon** [comment]
What do you think of the `directoryIndexes` and `removeDirectoryIndex` options in minurl? Boolean and a memoized map of filenames, and no regex.

**Comment by stevenvachon** [comment]
The shim [will soon have `URLSearchParams`](https://github.com/jsdom/whatwg-url/pull/87).

I've decided that it's best to wrap [minurl](https://npmjs.com/minurl) with:
* added support for string input (`URL` parsing)
* options abstracted and/or hidden

With that, there're currently two incompatibilities:
* minurl's [directoryIndexes](https://www.npmjs.com/package/minurl#directoryindexes)/[removeDirectoryIndex](https://www.npmjs.com/package/minurl#removedirectoryindex) with normalizeUrl's [removeDirectoryIndex](https://github.com/sindresorhus/normalize-url#removedirectoryindex)
* minurl has no [removeQueryParameters](https://github.com/sindresorhus/normalize-url#removequeryparameters)

**Comment by sindresorhus** [comment]
> I'm thinking of mirroring normalize-url in these two situations

👍

**Comment by stevenvachon** [comment]
@sindresorhus while I'm thinking of it, minurl has a [removeEmptyDirectoryNames](https://npmjs.com/minurl#removeemptydirectorynames] option. Based on the opinionated nature of normalize-url, I'd think that this option should be enabled by default (once wrapping minurl). Agree?

**Comment by sindresorhus** [comment]
Agreed, but I think the naming of it could be better. I would name it `removeDuplicatePathSeparators` or `collapsePathSeparators`.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/normalize-url/pull/59
