### ISSUE TITLE
Make protocol-relative URLs & www trimming optional?

### ISSUE THREAD

**Issue by ben-eb** [sindresorhus/normalize-url#4]
Would you be open to supporting an options object that could ignore these parameters?

```js
var url = '//www.domain.com/example.png';
console.log(normalize(url, { keepProtocol: true });
// => //domain.com/example.png
```

```js
var url = '//www.domain.com/example.png';
console.log(normalize(url, { keepWww: true });
// => http://www.domain.com/example.png
```

I'd like to use this module (with the PR I submitted) to normalise URLs, but I don't want to change their semantics. I'm happy to send a PR for this if you think its a good addition.

edit: ... should really check the issues tracker (#2) before posting an issue. But for my use case I would like to be able to keep the semantics of the URL as much as possible. `//` is not the same as `http://`.

**Comment by sindresorhus** [comment]
Why? What's your use-case for these options?

**Comment by ben-eb** [comment]
I'd like to develop a postcss plugin that normalises urls in CSS files.

**Comment by sindresorhus** [comment]
Ok, sure.

I don't see the point of `keepWwww` though as it doesn't really change the semantics as `http://domain.com` should always resolve to the same as `http://www.domain.com`.

**Comment by ben-eb** [comment]
OK, fair enough. I don't see it being a problem in the majority of use cases, either; and typically for my own needs I use protocol relative URLs instead. Might be better to handle that case if it comes up (though unlikely).

**Comment by sindresorhus** [comment]
Ok, cool. So PR welcome for an `keepProtocol` option.
