### ISSUE TITLE
'/' should not be normalized to an empty string

### ISSUE THREAD

**Issue by maxammann** [sindresorhus/normalize-url#56]
'/' is no URL but normalize-url should be able to handle the file part of an URL.
So currently '/' gets normalized to an empty string which is not an acceped input of normalize-url.
Take this example which throws the error 'Invalid URL':

```
var normalize = require("normalize-url")

console.log(normalize(normalize('/')))
```
(https://runkit.com/embed/al73fsrj4bw0)

imo an empty string should normalize to an empty string.

**Comment by sindresorhus** [comment]
I dunno. Supporting relative URLs is a slippery slope.

**Comment by maxammann** [comment]
So I'd propose that an empty string normalizes to an empty string without an error.

**Comment by sindresorhus** [comment]
I'm gonna follow the WHATWG standard here and it throws:

```
> new URL('/')
TypeError [ERR_INVALID_URL]: Invalid URL: /
    at onParseError (internal/url.js:237:17)
    at parse (internal/url.js:246:3)
    at new URL (internal/url.js:321:5)
```
