### ISSUE TITLE
unescape fallback ?

### ISSUE THREAD

**Issue by zidsi** [sindresorhus/normalize-url#58]
I've run normalize-url over number of urls - some of them older date. "Age" is of relevance since many of them include url **escaped** titles.

Such URL-s that contain (non utf-8) escaped characters fail with _URI malformed_  - being (mostly) in fact valid URLs. 

So I wrap normalize-url with try... catch and rerun normalize-url with normalizeUrl(unescape(urlstring)).

While this work around works well, it would be nice to have option like unescapeFallback (default false wouldn't change existing behavior) that would try to use unescape instead of decodeURI when decodeURI fails (non UTF-8 chacacters).

**Comment by sindresorhus** [comment]
Sorry, I'm not interested in supporting anything other than UTF-8 URLs.
