### ISSUE TITLE
Normalize to HTTPS protocol

### ISSUE THREAD

**Issue by venikman** [sindresorhus/normalize-url#62]
We don't have any option to get `https...` protocol if we didn't pass it. Only if your inout will start with `https://example.com` you could get output with `https`. Also I want to discuss about making it default to support security in web, so people still use unsafety  way they will have to do more setup, by that way we will force them to use `https` .   
> Make WEB safe again.

**Comment by sindresorhus** [comment]
I too wish we could just default to normalizing to HTTPS, but that would not work in practice as `http` always works, but a lot of URLs don't work when using `https`.

What's your use-case for wanting it to normalize to `https`?

**Comment by venikman** [comment]
I was using that generator for project, There is asked for my web-page url. I inputed `example.com` and after I created I found my `package.json` has `http://example.com`. But I has `https`. So I decided to open PR to fix it. After I saw that it using that module I came here but I didn't found any option for that. SO that fix help me to fix another fix =)

**Comment by sindresorhus** [comment]
Ok. I guess we could add a `normalizeHttp` method which would be mutually exclusive to `normalizeHttps`.
