### ISSUE TITLE
[3.x] React Native: Creating URL objects is not supported yet.

### ISSUE THREAD

**Issue by joncursi** [sindresorhus/normalize-url#63]
This may be more of a react native issue than `normalize-url`, but the new 3.x package is not compatible with React Native. I'm getting the follow error:

![screen shot 2018-06-05 at 3 35 22 pm](https://user-images.githubusercontent.com/4974609/40998620-5bd60630-68d6-11e8-9080-a660c04b8189.png)

Is there a way to use a fallback to make this work, or do I need to just downgrade the package on native?

**Comment by sindresorhus** [comment]
This module is for Node.js. It's up to you to figure out how to make it work in other environments. Probably easiest to just downgrade.

**Comment by timothywangdev** [comment]
same here, the above comment is very unhelpful

**Comment by acidfreako** [comment]
got the same error on react native while working with web3 socket URL

**Comment by pdaivik** [comment]
> got the same error on react native while working with web3 socket URL

hello did you find the solution for the error?

**Comment by MJO9** [comment]
Same here :( 

Any solution yet?
