### ISSUE TITLE
[3.x] Incompatible with Microsoft Edge

### ISSUE THREAD

**Issue by joncursi** [sindresorhus/normalize-url#68]
When I invoke `normalizeUrl(...)` on Microsoft edge, I get the following error:

```
TypeError: Unable to get property 'keys' of undefined or null reference
```

I believe this is caused by the following line:

https://github.com/sindresorhus/normalize-url/blob/f8245ac11c14b3db737d34809534f0c336da7503/index.js#L88

Downgrading to `2.0.1` is my temporary work-around for the issue.

**Comment by Kikobeats** [comment]
You can target properly the library transpiling it using babel

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
