### ISSUE TITLE
Add `url` as optional dependency?

### ISSUE THREAD

**Issue by dzek69** [sindresorhus/normalize-url#83]
This library depends on `url` on some environments, but it's not listed as optional dependency. IMO it should list it.

Why libraries should state optional dependencies?
1) to avoid confusion when trying to use the library
2) so user will know the correct dependency version library works with

Please add it

**Comment by sindresorhus** [comment]
The `url` module is a core Node.js module and should not be listed in package.json at all.

**Comment by sindresorhus** [comment]
https://nodejs.org/api/url.html

**Comment by dzek69** [comment]
This assumes you only want your package to be used in Node environment.
I'm using it with React Native and could want to use it on web with older browsers. But on the other hand - having this installed on Node environment is a waste.

I guess the current behavior is the most right one then.
