### ISSUE TITLE
'Reflect' is undefined

### ISSUE THREAD

**Issue by mrbaker4** [sindresorhus/normalize-url#86]
I recently upgraded to the latest version of `normalize-url` but ran into an issue when supporting IE. `Reflect` is not supported by IE. 

There is a comment for a `TODO` to remove the `Reflect` checks. 
1. Is there a reason they have not been removed yet? 
2. Do they still need to be there? 
3. If they still need to be there, can they be replaced with:
```
if ('normalizeHttps' in options)) {
  throw new Error('options.normalizeHttps is renamed to options.forceHttp');
}
```

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/normalize-url/pull/87#issuecomment-456668738

**Comment by sindresorhus** [comment]
While removing those checks might fix your immediate problem, I'm not interested in committing to supporting IE. I might introduce Reflect somewhere else in a patch version later on.
