### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by shchedrakov** [sindresorhus/normalize-url#92]
```
options = {
	defaultProtocol: 'http:',
	normalizeProtocol: true,
	forceHttp: false,
	forceHttps: false,
	stripAuthentication: true,
	stripHash: false,
	stripWWW: true,
	removeQueryParameters: [/^utm_\w+/i],
	removeTrailingSlash: true,
	removeDirectoryIndex: false,
	sortQueryParameters: true,
	...options
};
```
What is it the string `...options`? It is a cause if critical error in  Edge browser.  Can you remove  it from the code?

**Comment by merijndejonge** [comment]
Check out https://github.com/Polymer/tools/issues/173. Rather frustrating.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
