### ISSUE TITLE
Normalize domain names to lowercase

### ISSUE THREAD

**Issue by millette** [sindresorhus/normalize-url#98]
Since domain names are [case insensitive](https://tools.ietf.org/html/rfc4343), I'd like an option to normalize
"**S**indre**S**orhus.com"
into
"http://sindresorhus.com"
while keeping the path and query strings intact.

It would make finding duplicate URLs slightly easier.

**Comment by sindresorhus** [comment]
I don’t think there’s any reason for an option for this. Let’s make it default behavior and do a major release.

**Comment by millette** [comment]
Even better :-) I can take a stab at a PR if no-one else is.

**Comment by millette** [comment]
See #99 - although it already works as expected. I only added a test.
